name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - name: Run tests
        run: go test -cover ./...
      - name: Run tests for cmd/pps-simulate
        working-directory: cmd/pps-simulate
        run: go test -cover ./...
      - name: Run benchmarks
        run: go test -bench .
